{% set name = "pudu" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 7eb0c21a966b0e960e6bc277783c03439a5065280095409b2ad52be695c9811b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base
    - numpy
    - pandas
    - python >=3.6
    - scikit-learn
    - spectrapepper
    - tensorflow ==2.11

test:
  imports:
    - pudu

about:
  home: https://github.com/pudu-py/pudu
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python library for explainability of machine learinng algorithms in an agnostic, deterministic, and simple way.
  doc_url: https://pudu-py.github.io/pudu/
  dev_url: https://github.com/pudu-py/pudu

extra:
  recipe-maintainers:
    - enricgrau
